#!@bash@

@sketchybar@ --bar position=@bar_position@ height=@bar_height@ color=0xff@bar_color@

default=(
        label.font="@font_family@:Bold:@font_size@"
        label.color="0xff@text_color@"
)

@sketchybar@ --default "${default[@]}"

@sketchybar@ --add item front_app left \
             --set front_app icon.drawing=off label="" script="@front_app_script@" \
             --subscribe front_app front_app_switched

@sketchybar@ --update